# Generated by Django 4.0.3 on 2022-03-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_album_album_client_album_cover_photo_album_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='posts/albums'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/photos'),
        ),
    ]
